DBCC CHECKIDENT ("Clients",RESEED,0);
DBCC CHECKIDENT ("Softwares",RESEED,0);
DBCC CHECKIDENT ("Statuses",RESEED,0);
DBCC CHECKIDENT ("Clients", NORESEED);
DBCC CHECKIDENT ("Softwares",NORESEED);
DBCC CHECKIDENT ("Statuses",NORESEED);